"""
Django settings for tickets_with_miles project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j$@ym8s@c_36eyxhv5*c(h)u*_d755*dbubu6*ihf0nrs(%7b('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'flights',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tickets_with_miles.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tickets_with_miles.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Keys to flights api call
FLIGHT_API_KEY = 'aJqPU7xNHl9qN3NVZnPaJ208aPo2Bh2p2ZV844tw'
AKAMAI_TELEMETRY = 'a=&&&e=cGw5cDZYcVY5b2Vib1Nmc3pSOVpwTkoveXFkL3hQdkM3UWMwcUNGd2JaMmtDN3J6N3JIZ3l2YThCeW5lcjRqT29GVFRzRkM3L25BUU9iL2NFRFF3Qy9ibGJWSFJUdHZhbWxjc0hQc3Mrd1J6b1gvRUNPTEQ5NmtkNzN4UnFLNVZqZzJaejRMemt1cE44b2QvUlFsM2gzZDgxck1OMHpsVWlkUnJrdjRRV3JCd0ZYcXhvV291bXBacnZxcStDRzBLT2w=&&&sensor_data=Mjs4ODg4ODg4Ozc3Nzc3Nzc7MzAsMSwwLDAsNCwzNTtdJlosWm4mMXEzOGgqbEkqQzpfNzNQMSM9dGQjM1I1KDVlZkB9Nk8yJVtJI1RSXUReP0BzI0E7QjpXMHBuV1tWXj1JIF8rOTN+PHktOislJXlDeFheJSMrL1E1bSV2cGsjdChJM19CfHs9S29qaDUtc3A/dDJhV15+UDF9cFJaLTEgM3NpL3RQVnk5I21aNzclJFU4WjU9OV5WUUdIe1kzd35Kb2k6KXJgZChPVEMpW2tqRix4b0lSRzwvKEwjeGxsfT5aIT8lLThoP0MhOHQ3ei9sZD1ib25BSF1lZnVOdkw2TjYzZy5xU1J9Zk4/a0JzeGVmKWggOXJBSU4jaDRUdDNCbyFkeH4uaE1dLUJAUVNjT1ErcXlAe2RuZzZHaStSeWlwe2dYXiBbPTMhSj9gYzdwYkxIWmpVVVddfktofWt7a3B+dXVzcFs3c18jIz9Fb3FmYEhvKHhxJSZecU5uP14+RGM/R1opfSNmcC5fWHAmL0RKc0ZselRxJFZHJCA0JVNBLyAmRGdeU2c7N0lBJXNQP1Z7TFFvd1lwR01eVkFBRl17RHtNRj1gWFIrQ21UJFtNd293SkVFQ1U6WVElKDt0RHhWZztsaWdKMmAsYyNYX34mdVUzRUA+W2pAPXUuQUVwOEFMYDU5OGJFUHVPSUVlVyxmdHNXaTFkQHpDJHZdaTNod15rVi1XIUxJdCZPZFB8fC9wVGBuQXZkTkR7e2BOe15sdnBPaGA/ZlFpUSNpKV1jLGROb3JaL3hpY2pRQz1aPFl6YENlbz8uMHFOK201M0xaSC1NViBqc1ZVeGV3I2F0d3sodzo9QjklLSx0LChTX3psWDwoIWUhPU14U3p0biRGc19HIC9hU09HPndxRStCa2RTfGhQP0I3JkF3aHRUPyVyPDN9OXd6OiNxZ25gfkZjICtZKnIvTj5YYTkyOzIoRSApJlR0aEc+Kj9BcllSMENDQn5HVjE/RWNtLjFDMjJ1MjlJNkA0fXxsIzJqV0wjSWJlO31yWnl9SUtydj4sLFY/WHcxbmdNSlFXTFZDQG9EUWlKKCpFPUZ9R1RVfnV8U0FTZ0MhdnJMPmEqN1tLJkRRZig4Zzhja3JXUTxRYjtMXVBdTVZ+UF46eiVlWTRKemoyfTI4b3UmVXBIWlc7QCpKXllDe116NkNobzV+LW5hfkhbfWU7PSZlVS50RFhtYlZHcSlASHxIc3F1PDl8a1NJUURXSCwsJWQoYigufWAwJHVncCozRi1BeCFCT19JTnc+Oy1RZz9oVSliMmIjSVYwaDUzITpJICptb0hUelVrO2lhXitndykqRzo4ayRTTVMrY1NbenpafWhbQE8uWmRFISktTndUKXNQUnBXIElSVz1wcXEwSy9VeytLbj5XaDwrMi9bMm1JUz58WEJkPVByNiAlLWFnSHNuemEgSFVNOiQyM3k7OX0wTU8pc0UmQUMwai8xaSluPXVJMlcrL0wgciY1I1VJISZre3hGLGh0NnRrJCtfLm51cnZMcSw/UG5bcSl4ZzcwMngla3Q+LT1nWEZrOlMhdkY2Z0pocys/PTVKd1k1OyYxLEB4JmpoYzYveEhkOHNyPzh5fUZ6O3N3XSpNN28gLCAlOH00aGAsWWBNfEF+YEg4JltDM3E+WGBxRHJqWFFmQ0RnYC19cVppZlBzOCB3PElKPEE1JHxfcHg8dG90KzFJVWgzaUpLdEV0IVQ8dGJrOH1wflhiKio5OnVMTzFXY30qTEtlV18/c3sobTghen4xIHgtbWY7JD5OOWRFQn5WKCxRfUA7RTBjeyNeQTw2PTBPQUtHQHZecy5zQ0tbJiVTazlQamp8V1NtcjoodDlMSGVxeGprWEBKalk0REcgL2Qwb2o2MUw5IEpeQCw9N0VJdCA/Nzd2aylGOCYtMDppSWNed1hxZVlbLjIzb3QgOkdmeT42SDokanBnYG8xXnZSelYvXmMyfHQ5ZGc8XmQtPlZ1Mz9RP0dpNyUrRVIwVTdvWylQZk5lbypgcjMqMXZifEMqYk8+ak0yZylEazhrWDA2aklTNi84YEZPOl9ZK2JdL0tZJURSeFJNQnBzKzFHfVQwZVpNfSlhdHpNY3VaeXh4UGE1NDpsTmdiK1ZDd21XTzlkOnM3cmJDSU4gMHU2c0wrOWl2eWFBbFY6ZVQyJWVkUDBqS15nST49QnYydE1NVT5xUzdDTSZWSChXYSMhWXhpVTRzJFUubzM/Zj5QW0AtZ2BdcENLRHx7cnpSPEUqNHkkKF12TUJVNHBdUnFfZjVKSyFPd2ZLXnNJNDkhLXg2IHtfSWI4eXM9djdrVzYuaFtJIU5YTD92UWVPQUNNXzdUTVg+Z2AgKjRgXlF+YVZYLHZhc05rWi09PXVCfC0xTjhOWXxUL0h6X0RlPERTMyR7aVRlQ1pLZ0pOJj86WjQzKi0mY1szIWMzRSFtZk9YUyw7L100R0RUJjspdlp4MFNacFVvQHckbGhENXclKVZYYlAlMXAgLnJUYkpoRDRObk9pYmFDMj1LI1hbPU5SUT1FREB0WThwZT50YzNFaClTYCgrKXNfaiBBfTR2OjEjb3JUVDt8NF4+KGlWcHNDYyZNISVXPyUwPCR0aGdlOFZSQF51VTdVe2xibTpHYDFfLFYwMnFRO0tsMz1KQm5nO0Y9YmhhWG9dPjJFTntAV0c0Y0tIVU49Zy59Si01T2oyRzF5dF9mMlJadl8oZE18JnNFICpNfUh6RD85UyY6PWh5R01vOGE5Y2BlLnx7dzJ1I3ZQIEM6WnZET1BYeDBgL1shbFFNVCZmckA2fT5vISV0VD9UPS89TUxKUWZ1W3Ywb1JgajAuYUdXV15VPndyPmB4XyVgakE0cyFjaDloLV0vYTVRYVBHOURbW0g+eX5eTWg+Wy5CV1ErIz50LG4lckpGVns0SVF3JTpvYjF9bmI4aGQrJCM+LSEuQ3NHKks+eFYqV2Ajd114OHtKUUhRQUBfaWFwJTsxSGJ8bHBlSit2WXxhfjExcUNnPCEhZ310IGp6UDBeKGxtfDstKyRkJmY6aktVRXp3QFlxKzMvJlZrZ1pMdzVmVC1JaFV8e15EfXFIW09sd31AOSFzdGUoKV03Szg+UXckKFd1Yj5FJSt5bEEwSXRrQWI6Ln4xMUFNaG8qZGJIOHMlRXtmSk9GR0RCJmpAbnYwaTMzJjExbHhFOU1MRHBPZTdCcGJeX1hlVmBDQm1MYG5LKi96SFNkIUVafmp2Vjc7VzBkY1ZZVXZqNmlAOiAwfGFzS3wxSW9fWGdXN3F7XXhWdHpUclIqd29WIVBacSh5ZEdMLiA5bC9VPD10IGErTGlKU1gqQUZkPTB6JGRMe1V7diYlV3ZPalZpOEV0OzthMl5JXld0M0xVc3QqayF6TDs9SWB+TyVSPFM='
